name: Feature Request
description: Create a feature request.
title: "[⭐]: "
labels: ["enhancement"]
type: feature
body:
  - type: markdown
    attributes:
      value: |
        Thanks for participating in this project!
        Please fill out the following sections to help us understand what you want.

        In any case,
          - make sure you are using the latest version of the extension;
          - do at least one search in current issues or feature requests, there might be a similar request already where you could help out;
          - do include as many details as possible;
  - type: textarea
    id: requested-feature
    attributes:
      label: What feature would you like to see added?
    validations:
      required: true
  - type: textarea
    id: current-behavior
    attributes:
      label: If it is related to current behavior, what is the current behavior?
  - type: textarea
    id: additional-information
    attributes:
      label: do you have any additional information for us?
  - type: checkboxes
    attributes:
      label: Is there an existing Feature Request/PR for this?
      description: Please search to see if a feature request or PR already exists for the feature you would like.
      options:
      - label: I have searched the existing issues and pull requests
        required: true
  - type: checkboxes
    attributes:
      label: Are you willing to create a pull request for this?
      description: Thank you so much for your willingness to help us out! We really appreciate it.
      options:
      - label: I would be willing to create a pull request for this feature
